api/urls.py
from django.urls import path
from .views import SubscriberAPIView

urlpatterns = [
    path('subscriber/', SubscriberAPIView.as_view(), name='subscriberapi'),
]

calculator/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("calculator/", views.calculator, name="calculator"),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("services/", views.services, name="services"),
    path("services/<slug:slug>/", views.service_detail, name="service_detail"),
    path("blogs/<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("blogs/", views.blog, name="blogs"),
    path("excell/", views.Excell_templateWiev.as_view(), name="excell"),
    path("excell/<int:pk>/", views.ExcellDetail.as_view(), name="excell"),
    path("excell/<int:pk>/<str:status>/", views.ExcellDetail.as_view(), name="excell"),
    path("set_language/<str:lang>/", views.set_language, name="set_language"),
]

just_finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('metal/', admin.site.urls),
    path('translation/', include('rosetta.urls')),
    path("", include("core.urls")),
    path("", include("calculator.urls")),
    path("api/", include("core.api.urls")),
    path("api/", include("calculator.api.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

calculator/models.py
from django.db import models


# Create your models here.


class InsuranceFee(models.Model):
    from_number = models.FloatField()
    to_number = models.FloatField()
    from_to_formula = models.CharField(max_length=255, blank=True, null=True)
    to_from_formula = models.CharField(max_length=255, blank=True, null=True)
    insurance_type = models.ForeignKey(
        "InsuranceType", on_delete=models.CASCADE, related_name="fees", blank=True, null=True
    )

    def __str__(self):
        if self.from_to_formula:
            return f"{self.from_number} - {self.to_number} - {self.from_to_formula}"
        else:
            return f"{self.from_number} - {self.to_number} - {self.to_from_formula}"


class InsuranceType(models.Model):
    """
        Sığortaolunan,
        Sığortaedən
    """
    NAME_CHOICES = (
        ("Sığortaolunan", "Sığortaolunan"),
        ("Sığortaedən", "Sığortaedən"),
    )
    name = models.CharField(max_length=255, blank=True, null=True, choices=NAME_CHOICES)
    tax_type = models.ForeignKey("TaxType", on_delete=models.CASCADE, related_name="insurance_types", blank=True,
                                 null=True)

    def __str__(self):
        return f"{self.name} - {self.tax_type.name}"

    class Meta:
        verbose_name = "Insurance Type"
        verbose_name_plural = "Insurance Types"


class TaxType(models.Model):
    """
        Gəlir vergisi,
        Sosial sığorta haqqı,
        İşsizlikdən sığorta haqqı,
        İcbari tibbi sığorta
    """
    NAME_CHOICES = (
        ("Gəlir vergisi", "Gəlir vergisi"),
        ("Sosial sığorta haqqı", "Sosial sığorta haqqı"),
        ("İşsizlikdən sığorta haqqı", "İşsizlikdən sığorta haqqı"),
        ("İcbari tibbi sığorta", "İcbari tibbi sığorta"),
    )
    sector_type = models.ForeignKey("SectorType", on_delete=models.CASCADE, related_name="tax_types", blank=True,
                                    null=True)
    name = models.CharField(max_length=255, blank=True, null=True, choices=NAME_CHOICES)

    def __str__(self):
        return f"{self.name} - {self.sector_type.name}"


class SectorType(models.Model):
    """
        Neft-qaz sahəsində fəaliyyəti olmayan və qeyri-dövlət sektoruna aid edilən,
        Neft-qaz sahəsində fəaliyyəti olan və dövlət sektoruna aid edilən
    """
    NAME_CHOICES = (
        ("Neft-qaz sahəsində fəaliyyəti olmayan və qeyri-dövlət sektoruna aid edilən",
         "Neft-qaz sahəsində fəaliyyəti olmayan və qeyri-dövlət sektoruna aid edilən"),
        ("Neft-qaz sahəsində fəaliyyəti olan və dövlət sektoruna aid edilən",
         "Neft-qaz sahəsində fəaliyyəti olan və dövlət sektoruna aid edilən"),
    )
    name = models.CharField(max_length=255, choices=NAME_CHOICES)

    def __str__(self):
        return self.name

calculator/api/views.py
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from calculator.models import SectorType, InsuranceType


class CalculatorView(APIView):
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        sector_type = get_object_or_404(SectorType, id=request.data.get("sector_type"))
        from_number = request.data.get("from_number")
        to_number = request.data.get("to_number")
        from_number = float(from_number) if from_number else None
        to_number = float(to_number) if to_number else None

        if from_number:
            qs_filter = {
                "from_number__lte": from_number,
                "to_number__gt": from_number,
                "from_to_formula__isnull": False,
            }
        elif to_number:
            qs_filter = {
                "from_number__lte": to_number,
                "to_number__gt": to_number,
                "to_from_formula__isnull": False,
            }
        else:
            return Response(
                {"error": _("Please provide from_number or to_number")},
                status=status.HTTP_400_BAD_REQUEST,
            )
        data = []
        input_value = 0
        for tax_type in sector_type.tax_types.all():
            for insurance_type in tax_type.insurance_types.all().order_by("name"):
                insurance_fees = insurance_type.fees.filter(**qs_filter).order_by("insurance_type__name")
                for insurance_fee in insurance_fees:
                    try:
                        value = eval(insurance_fee.from_to_formula or insurance_fee.to_from_formula, {},
                                     {'x': from_number or to_number})
                    except ZeroDivisionError:
                        value = 0
                    if insurance_type.name == InsuranceType.NAME_CHOICES[0][0]:
                        if from_number:
                            input_value -= value
                        else:
                            input_value += value
                    row = {tax_type.name: value}
                    data.append(row)

        res = dict()
        for item in data:
            for i in item:
                if i in res:
                    res[i] += [item[i]]
                else:
                    res[i] = [item[i]]
        return Response(
            {
                "data": res,
                "input_value": input_value,
            },
            status=status.HTTP_200_OK)

calculator/views.py
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from calculator.models import SectorType, InsuranceType


# Create your views here.


def calculator(request):
    context = {
        "title": _("Calculator"),
        "sector_types": SectorType.objects.all(),
        "insurance_type_names": [insurance_type[0] for insurance_type in sorted(InsuranceType.NAME_CHOICES, key=lambda x: x[1])],
    }
    return render(request, "pages/calculator.html", context)

core/api/views.py
from rest_framework.views import APIView
from rest_framework import permissions, status
from rest_framework.response import Response

from core.api.serializers import SubscriberSerializer, ContactSerializer
from django.utils.translation import gettext_lazy as _

from core.models import Contact


class SubscriberAPIView(APIView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request):
        serializer = SubscriberSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            message = {'success': True,
                       'message': _('Successfully subscribed.')}
            return Response(message, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ContactAPIView(APIView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request):
        serializer = ContactSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            message = {'status': 'success',
                       'message': _('Successfully sent.')}
            return Response(message, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

core/views.py
from django.conf import settings
from django.http import FileResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import activate, gettext_lazy as _

from django.views.generic import ListView

from calculator.models import SectorType
from core.models import About, HR, FAQ, ApplicationCategory, Service, Blog, Excell_template, ServiceFAQ


def index(request):
    context = {
        "title": _("Home"),
        "about": About.objects.last(),
        "hr": HR.objects.last(),
        "faqs": FAQ.objects.all(),
        "services": Service.objects.all()[:4],
        "blogs": Blog.objects.filter(is_pin=False)[:2],
        "blogs_pin": Blog.objects.filter(is_pin=True)[:1],
        "applicationcategory": ApplicationCategory.objects.all(),
        "media_url": settings.MEDIA_URL,
        "sector_types": SectorType.objects.all(),
    }
    return render(request, "pages/v2index.html", context)


def about(request):
    context = {
        "title": _("About"),
        "about": About.objects.last(),
        "hr": HR.objects.last(),
        "faqs": FAQ.objects.all(),
    }
    return render(request, "pages/about.html", context)


def contact(request):
    context = {
        "title": _("Contact"),
        "applicationcategory": ApplicationCategory.objects.all(),
        "about" : About.objects.last(),
    }
    return render(request, "pages/contact.html", context)


def services(request):
    context = {
        "title": _("Services"),
        "services": Service.objects.all().order_by('-id'),
    }
    return render(request, "pages/v2services.html", context)


def service_detail(request, slug):
    context = {
        "title": _("Service Detail"),
        "service": Service.objects.get(slug=slug),
        "servicesfaq": ServiceFAQ.objects.filter(service=Service.objects.get(slug=slug)),

    }   
    return render(request, "pages/v2service-detail.html", context)


def blog(request):
    context = {
        "title": _("Blog"),
        "blogs": Blog.objects.all(),
    }
    return render(request, "pages/blogs.html", context)


def blog_detail(request, slug):
    context = {
        "title": _("Blog Detail"),
        "blog": Blog.objects.get(slug=slug),
    }
    return render(request, "pages/blog-detail.html", context)


def set_language(request, lang):
    response = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang)
    activate(lang)
    return response


class Excell_templateWiev(ListView):
    model = Excell_template
    template_name = "pages/v2excel.html"
    context_object_name = "excell_template"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        # context["excell"] = Excell_template.objects.all()
        context = super().get_context_data(**kwargs)
        context["title"] = _("Excell Template")
        context["excell_template"] = Excell_template.objects.all()
        context["categories"] = ApplicationCategory.objects.all()
        category = self.request.GET.get("category_id")
        search = self.request.GET.get("search_excel")
        if search:
            context["excell_template"] = Excell_template.objects.filter(title__icontains=search)
        if category:
            context["excell_template"] = Excell_template.objects.filter(category__id=category)
        if category and search:
            context["excell_template"] = Excell_template.objects.filter(title__icontains=search, category__id=category)
        
        context["search"] = search
        context["selected_category"] = category
        return context


class ExcellDetail(ListView):
    def get(self, request, pk, status=None):
        try:
            excell = Excell_template.objects.get(pk=pk)
        except:
            return "File does not exist"
        response = FileResponse(open(excell.file.path, 'rb'))
        if status == 'download':
            response['Content-Disposition'] = 'attachment; filename=%s' % excell.file.name
        elif status == 'show':
            response['Content-Disposition'] = 'inline; filename=%s' % excell.file.name
        return response

templates/components/about-detail.html
{% load static %}
<section class="about section-padding" id="section_2">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-12">
                <h2 class="mb-5">Digital Happiness</h2>
            </div>

            <div class="col-lg-4 col-12 ms-lg-auto mb-5 mb-lg-0">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="nav-intro-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-intro" type="button" role="tab" aria-controls="nav-intro"
                                aria-selected="true">Introduction
                        </button>

                        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-profile" type="button" role="tab"
                                aria-controls="nav-profile" aria-selected="false">HR
                        </button>

                        <button class="nav-link" id="nav-faq-tab" data-bs-toggle="tab" data-bs-target="#nav-faq"
                                type="button" role="tab" aria-controls="nav-faq" aria-selected="false">FAQs
                        </button>
                    </div>
                </nav>
            </div>

            <div class="col-12">
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-intro" role="tabpanel"
                         aria-labelledby="nav-intro-tab">
                        <div class="row">
                            <div class="col-lg-6 col-12 mb-lg-0 mb-4">
                                <img src="{{ about.image.url }}"
                                     class="img-fluid" alt="">
                            </div>

                            <div class="col-lg-5 col-12 m-auto">
                                <h3 class="mb-3">{{ about.title }}</h3>

                                <p class="mb-4">{{ about.description|safe }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="nav-profile" role="tabpanel"
                         aria-labelledby="nav-profile-tab">
                        <div class="row">
                            <div class="col-lg-5 col-12 m-auto">
                                <h3 class="mb-3">{{ hr.title }}</h3>

                                <p>{{ hr.description|safe }}</p>

                                {% comment %}
                                        <ul class="social-icon mt-lg-5 mt-3">
                                            <li class="me-3"><strong>Where to find?</strong></li>

                                            <li><a href="https://twitter.com/search?q=tooplate"
                                                   class="social-icon-link bi-twitter"></a></li>

                                            <li><a href="#" class="social-icon-link bi-linkedin"></a></li>

                                            <li><a href="#" class="social-icon-link bi-envelope"></a></li>
                                        </ul>
                                        {% endcomment %}
                            </div>

                            <div class="col-lg-6 col-12 mt-lg-0 mt-4">
                                <img src="{{ hr.image.url }}"
                                     class="img-fluid" alt="">
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="nav-faq" role="tabpanel" aria-labelledby="nav-faq-tab">
                        <div class="row">
                            <div class="col-lg-6 col-12 mb-lg-0 mb-4">
                                <img src="{% static 'images/php-programming-html-coding-cyberspace-concept.jpg' %}"
                                     class="img-fluid" alt="">
                            </div>

                            <div class="col-lg-5 col-12 m-auto">
                                <h3 class="mb-3">Frequenlty Asked Questions</h3>
                                <div class="accordion" id="accordionGeneral">
                                    {% for faq in faqs %}
                                        <div class="accordion-item">
                                            <h2 class="accordion-header" id="heading{{ faq.id }}">
                                                <button class="accordion-button collapsed" type="button"
                                                        data-bs-toggle="collapse"
                                                        data-bs-target="#accordionGeneralOne"
                                                        aria-expanded="true"
                                                        aria-controls="accordionGeneralOne">
                                                    {{ faq.question }}
                                                </button>
                                            </h2>

                                            <div id="accordionGeneralOne" class="accordion-collapse collapse"
                                                 aria-labelledby="heading{{ faq.id }}"
                                                 data-bs-parent="#accordionGeneral">

                                                <div class="accordion-body">
                                                    {{ faq.answer|safe }}
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

templates/components/blogs-detail.html
{% load static %}
<section class="work section-padding" id="section_4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="mb-5 text-center">Blogs</h2>
            </div>
            {% for blog in blogs %}
                <div class="col-lg-4 col-12">
                    <div class="work-thumb mb-4">
                        <div class="work-image-wrap">
                            <a href="{% if blog.image.url %} {{ blog.image.url }} {% endif %}"
                               class="image-popup">
                                <img src="{% if blog.image.url %} {{ blog.image.url }} {% endif %}"
                                     class="img-fluid work-image" alt="">
                            </a>
                        </div>

                        <div class="work-text-info">
                            {% comment %}
                                    <small class="work-tag bg-white shadow-lg">Art Direction</small>
                                    {% endcomment %}
                            <h4 class="work-title">{{ blog.title }}</h4>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
</section>

templates/components/calculator-form.html
{% load i18n %}
<section class="services section-padding" id="section_6">
    <div class="container">

        <form id="calculator-form" method="post">
            {% csrf_token %}
            <div>
                {% for type in sector_types %}
                    <input {% if forloop.first %} checked="checked" {% endif %} type="radio" name="sector_type"
                                                  value="{{ type.name }}" data-id="{{ type.id }}"
                                                  id="sector_type_{{ type.id }}">
                    <label for="sector_type_{{ type.id }}">{{ type.name }}</label>
                    <br>
                {% endfor %}
                <br>

            </div>
            <div>
                <label for="id_from_number">{% translate 'Gross maaş' %}</label>
                <input type="number" id="id_from_number">
                <i class="fa-solid fa-left-right" style="cursor: pointer" onclick="swapNumbers()"></i>
                <label for="id_to_number">{% translate 'Net maaş' %}</label>
                <input type="number" id="id_to_number" disabled>
            </div>
            <br>
            <table class="table" id="calculator-table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Tutulmalar</th>
                    {% for name in insurance_type_names %}
                        <th scope="col">{{ name }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody id="calculator-table-body">
                </tbody>
            </table>

        </form>
    </div>
</section>

<script>
    const calculatorForm = document.querySelector('#calculator-form');
    const fromNumber = document.querySelector('#id_from_number');
    const toNumber = document.querySelector('#id_to_number');
    const calculatorTableBody = document.querySelector('#calculator-table-body');

    calculatorForm.addEventListener('keyup', function (e) {
        e.preventDefault();
        const sectorType = document.querySelector('input[name="sector_type"]:checked');
        if (sectorType) {
            const sectorTypeId = sectorType.dataset.id;
            const url = '/api/calculator/'

            const data = {
                'sector_type': sectorTypeId,
            }
            if (toNumber.disabled) {
                data['from_number'] = fromNumber.value
            } else if (fromNumber.disabled) {
                data['to_number'] = toNumber.value
            }
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
                body: JSON.stringify(data)
            })
                .then(response => response.ok ? response.json() : Promise.reject(response))
                .then(data => {
                    total = {};
                    inputTotal = {};
                    html = '';
                    for (const [key, value] of Object.entries(data.data)) {
                        html += '<tr>';
                        html += '<td>' + key + '</td>';
                        for (const [item] of Object.entries(value)) {
                            html += '<td>' + parseFloat(value[item]).toFixed(2) + '</td>';
                            if (total[item]) {
                                total[item] += value[item];
                            } else {
                                total[item] = value[item];
                            }
                        }
                        if (inputTotal['total']) {
                            inputTotal['total'] += parseFloat(value[1]);
                        } else {
                            inputTotal['total'] = parseFloat(value[1]);
                        }
                        html += '</tr>';
                    }
                    html += '<tr>';
                    html += '<td>Toplam</td>';
                    for (const [key, value] of Object.entries(total)) {
                        html += '<td>' + parseFloat(value).toFixed(2) + '</td>';
                    }
                    html += '</tr>';
                    if (toNumber.disabled) {
                        toNumber.value = (parseFloat(fromNumber.value) + parseFloat(data.input_value)).toFixed(2);
                    } else {
                        fromNumber.value = (parseFloat(toNumber.value) + parseFloat(data.input_value)).toFixed(2);
                    }
                    calculatorTableBody.innerHTML = html;
                })
                .catch((error) => {
                    console.error('Error:', error);
                });
        }
    });


    function swapNumbers() {
        const fromNumber = document.querySelector('#id_from_number');
        const toNumber = document.querySelector('#id_to_number');
        if (fromNumber.disabled) {
            fromNumber.disabled = false;
            toNumber.disabled = true;
            toNumber.value = '';
        } else if (toNumber.disabled) {
            fromNumber.disabled = true;
            toNumber.disabled = false;
            fromNumber.value = '';
        }
    }

</script>

templates/components/calculator.html
{% load i18n %}
<section class="services mt-5 py-5 bg-light" id="section_6" style="margin-top: 20px;">
    <div class="container">
        <h2 class="mb-5 text-center">Kalkulyator</h2>
        <form id="calculator-form" method="post">
            {% csrf_token %}
            <div>
                {% for type in sector_types %}
                    <input {% if forloop.first %} checked="checked" {% endif %} type="radio" name="sector_type"
                                                  value="{{ type.name }}" data-id="{{ type.id }}"
                                                  id="sector_type_{{ type.id }}">
                    <label for="sector_type_{{ type.id }}">{{ type.name }}</label>
                    <br>
                {% endfor %}
                <br>

            </div>
            <div>
                <label for="id_from_number">{% translate 'Gross maaş' %}
                <input type="number" id="id_from_number">
                <i class="fa-solid fa-left-right" style="cursor: pointer" onclick="swapNumbers()"></i>
                <label for="id_to_number">{% translate 'Net maaş' %}
                <input type="number" id="id_to_number" disabled>
            </div>
            <br>
            <table class="table" id="calculator-table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Tutulmalar</th>
                    <th scope="col">Sığortaedən</th>
                    <th scope="col">Sığortaolunan</th>
                </tr>
                </thead>
                <tbody id="calculator-table-body">
                </tbody>
            </table>

        </form>
    </div>
</section>

<script>
    const calculatorForm = document.querySelector('#calculator-form');
    const fromNumber = document.querySelector('#id_from_number');
    const toNumber = document.querySelector('#id_to_number');
    const calculatorTableBody = document.querySelector('#calculator-table-body');

    calculatorForm.addEventListener('keyup', function (e) {
        e.preventDefault();
        const sectorType = document.querySelector('input[name="sector_type"]:checked');
        if (sectorType) {
            const sectorTypeId = sectorType.dataset.id;
            const url = '/api/calculator/'

            const data = {
                'sector_type': sectorTypeId,
            }
            if (fromNumber.value) {
                data['from_number'] = parseInt(fromNumber.value)
            } else if (toNumber.value) {
                data['to_number'] = parseInt(toNumber.value)
            }
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
                body: JSON.stringify(data)
            })
                .then(response => response.json())
                .then(data => {
                    total = {};
                    html = '';
                    data.sector_type.tax_types.forEach(function (tax_type) {
                        html += '<tr>';
                        html += '<td>' + tax_type.name + '</td>';
                        tax_type.insurance_types.forEach(function (insurance_type) {
                            html += '<td>' + (insurance_type.fee.fee > 0 ? insurance_type.fee.fee : '') + '</td>';
                            if (total[insurance_type.name]) {
                                total[insurance_type.name] += insurance_type.fee.fee;
                            } else {
                                total[insurance_type.name] = insurance_type.fee.fee;
                            }
                        });
                        html += '</tr>';
                    });
                    html += '<tr>';
                    html += '<td>Toplam</td>';
                    for (const [key, value] of Object.entries(total)) {
                        html += '<td>' + value + '</td>';
                    }
                    html += '</tr>';
                    if (toNumber.disabled){
                        toNumber.value = fromNumber.value;
                        for (const [key, value] of Object.entries(total)) {
                            toNumber.value -= value;
                        }
                        toNumber.value = toNumber.value;
                        calculatorTableBody.innerHTML = html;
                    } else if (fromNumber.disabled){
                        fromNumber.value = toNumber.value;
                        for (const [key, value] of Object.entries(total)) {
                            fromNumber.value -= value;
                        }
                        fromNumber.value = fromNumber.value;
                        calculatorTableBody.innerHTML = html;
                    }
                })
                .catch((error) => {
                    console.error('Error:', error);
                });
        }
    });


    function swapNumbers() {
        const fromNumber = document.querySelector('#id_from_number');
        const toNumber = document.querySelector('#id_to_number');
        if (fromNumber.disabled){
            fromNumber.disabled = false;
            toNumber.disabled = true;
            toNumber.value = '';
        } else if (toNumber.disabled){
            fromNumber.disabled = true;
            toNumber.disabled = false;
            fromNumber.value = '';
        }
    }

</script>